### ISSUE TITLE
through2 dependency missing

### ISSUE THREAD

**Issue by yamalight** [robrich/gulp-if#23]
If you try to use gulp-if after just running `npm install gulp-if`, you'll get the following error:

```
module.js:340
    throw err;
          ^
Error: Cannot find module 'through2'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (../node_modules/gulp-if/node_modules/ternary-stream/index.js:4:16)
```

It is easily resolved by running `npm install through2`. I can see that it's in dev-dependencies, but not in regular ones. Shouldn't it be included there as well?

Tested with node v0.10.26 and npm v1.4.7 on macos and debian.

**Comment by DevinXian** [comment]
when I updated node to v4.0.0, I found this question in module gulp-sass;  just remove the module and re install,  works fine now ,many thanks~

**Comment by SPxiaomin** [comment]
@DevinXian almost the same as your, I found this question in module gulp-plumber, do the same thing as you , done, works well , thanks ：）

**Comment by ul71m0** [comment]
Same here, that fixed it.

**Comment by egisberto** [comment]
Thanks.
